apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: registry
        image: registry:2.8.3
        ports:
        - containerPort: 5000
       
        env:
        - name: REGISTRY_HTTP_SECRET
          valueFrom:
            secretKeyRef:
              name: registry-secrets
              key: http-secret
        args: ["serve", "/etc/docker/registry/config.yml"]
        volumeMounts:
        - name: data
          mountPath: /var/lib/registry
        - name: cfg
          mountPath: /etc/docker/registry
        - name: auth
          mountPath: /auth
          readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: registry-pvc
      - name: cfg
        configMap:
          name: registry-config
          items:
          - key: config.yml
            path: config.yml
      - name: auth
        secret:
          secretName: registry-secrets
          items:
          - key: htpasswd
            path: htpasswd
