apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: registry
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
    http:
      addr: :5000
      # зафиксируй длинную случайную строку (64+ символов)
      secret: "CHANGE_ME_TO_LONG_RANDOM_STRING_64CHARS"
    auth:
      token:
        realm: http://192.168.31.125/jwt/auth
        service: container_registry
        issuer: gitlab-issuer
        # если позже включишь HTTPS с кастомным CA у GitLab:
        # rootcertbundle: /etc/ssl/certs/ca-certificates.crt
