apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: registry
data:
  config.yml: |
    version: 0.1
    log:
      level: info
    http:
      addr: :5000
      secret: ${REGISTRY_HTTP_SECRET}
      headers:
        X-Content-Type-Options: [nosniff]
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
    auth:
      htpasswd:
        realm: basic-realm
        path: /auth/htpasswd
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
